
spring:
  profiles:
    active: prod
  redis:
    host: ENC(CHXeT1pffOpImknDNtwIs3H6oIX1nCQJDSdECS5l6CO3d1oeao+Kbf58mNolyFxMFAqVYoavLlEXtAEq0kIEdQ==)
    port: 6379

jwt:
  secret: ENC(4hKFgzrCzw2rq7QmmvEK3NetjV7Cnuk+1ISkSmHI2RvINcQEowytV/YYS6bkn55/nTe8hkeCX34J633sh5rMcw==)

---

spring:
  config:
    name: local
    activate:
      on-profile: local
  resources:
    config-location: classpath:/application-local.yml

---

spring:
  config:
    name: prod
    activate:
      on-profile: prod
  resources:
    config-location: classpath:/application-prod.yml